# Generated by Django 3.1.5 on 2021-01-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhmsystem', '0002_remove_user_is_doctor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
