# Generated by Django 3.1.4 on 2020-12-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhmsystem', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='patient',
        ),
    ]
