# Generated by Django 3.1.5 on 2021-01-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhmsystem', '0003_auto_20210105_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
