# Generated by Django 3.1.4 on 2020-12-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhmsystem', '0004_auto_20201217_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhmsystem.doctor')),
            ],
        ),
    ]
