# Generated by Django 3.1.5 on 2021-01-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhmsystem', '0006_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Responses',
        ),
    ]
