# Generated by Django 3.1.5 on 2021-01-11 10:12

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhmsystem', '0007_auto_20210105_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
